apiVersion: apps/v1
kind: Deployment
metadata:
  name: botit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: botit
  template:
    metadata:
      labels:
        component: botit
    spec:
      containers:
        - name: flaskbuild
          image: dina2022/python-flask:${{ secrets.COMMIT_HASH }}
          ports:
           - containerPort: 9999
