name: build flask docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: Dinahalem/flask-docker
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dina2022/flaskdocker
        
            
  Run_container:
    name: run container
    needs: build
    runs-on: self-hosted  
    steps:         
    - name: Build container
      run: |       
          #docker stop test-devops
          #docker rm test-devops
          docker run -d -p 9999:9999 --name flaskbuild dina2022/flaskdocker
    
